export const NEWS = [
  {
    id: 20260329,
    title: "Axemen Throw Seamen Overboard",
    subtitle: "Axemen win back-to-back titles in thrilling 4-3 OT victory",
    date: "March 29, 2026",
    primaryImage: "/news-images/20260329.webp",
    images: [
      "newsfeed/2026-03-29/img1.webp",
      "newsfeed/2026-03-29/img2.webp",
      "newsfeed/2026-03-29/img3.webp",
      "newsfeed/2026-03-29/img4.webp",
      "newsfeed/2026-03-29/img5.webp",
      "newsfeed/2026-03-29/img6.webp",
      "newsfeed/2026-03-29/img7.webp",
      "newsfeed/2026-03-29/img8.webp",
      "newsfeed/2026-03-29/img9.webp",
      "newsfeed/2026-03-29/img10.webp",
    ],
    textBody: `In a thrilling championship matchup in front of a record crowd Friday night at the Gale Centre, the Axemen defeated the Seamen 4-3 in overtime to claim their second title in as many years.\n\nFrom the outset, the game lived up to its billing as a fast-paced, high skill showdown between the two top seeds. It was Carl Greco striking at 2:21 in the first to give the Seamen the early lead. It was short-lived, however, as Brett Audit tied the game only 48 seconds later. In the dying seconds of the first, Charlie Izaguirre snatched the lead for the Axemen with only 24 seconds left heading to the intermission.\n\nAt 1:18 of the second, Stephen Negus would double the lead to 3-1 for the Axemen as they looked to pull away from the top seed. The Seamen had other plans. Adam Quait netted one back at 5:08, and Matthew Maidens tied the game 3-3 at 9:05.\n\nStellar goaltending by both Reid Morgan of the Seamen and Cassidy Traver of the Axemen led to a scoreless third stanza and a deadlock after regulation. For the second time in three years, the CMHL title would be decided in the extra period. Luke Rymarchuk is the hero in this one after crashing the net and tapping in a rebound from a Jacob Saddler shot only 19 seconds into OT.\n\nWith the win, the Axemen have won back-to-back titles and become the first team in CMHL history to repeat as champions. The Seamen, coming over from CYO, had a tremendous year and made a strong case for a championship in their first season. Congratulations to both teams on an exciting season and thank you to all players, coaches, and fans for making the 2025-26 season a success! We hope to see you all back next season for more exciting CMHL action.`,
  },
  {
    id: 20260322,
    title: "Seamen, Axemen to Battle for CMHL Supremacy",
    subtitle:
      "Seamen take down Toonie Tuesday, while Axemen dispatch of Gulls to set up Final",
    date: "March 22, 2026",
    primaryImage: "/news-images/20260322.webp",
    images: [
      "newsfeed/2026-playoff-bracket-f.webp",
      "newsfeed/2026-03-22/img1.webp",
      "newsfeed/2026-03-22/img2.webp",
      "newsfeed/2026-03-22/img3.webp",
      "newsfeed/2026-03-22/img4.webp",
      "newsfeed/2026-03-22/img5.webp",
      "newsfeed/2026-03-22/img6.webp",
      "newsfeed/2026-03-22/img7.webp",
      "newsfeed/2026-03-22/img8.webp",
    ],
    textBody: `The Seamen and Axemen are set to face off next Friday in the 2026 CMHL Final after each earned wins in last night's semi-finals.\n\nFirst, the Seamen beat Toonie Tuesday in a tightly contested 5-3 game. Despite a two goal effort from Zack Keldson, the Seamen's Brad Pagetto scored to take an early lead and never looked back. The offense was led by Alex DiCarlo and Matthew Maidens who potted two each, and Reid Morgan shut the door in net to secure a CMHL Finals berth.\n\nThe late game saw a 2025 CMHL Finals rematch as the Axemen took down the Gulls 7-3. Cesare Caldaroni opened the scoring to grab the lead late in the first for the Gulls, but seven unanswered goals ultimately secured the win for the Axemen. Two tallies each by Luke Rymarchuk and Stephen Negus led the charge for the Axemen and solid goaltending from Cassidy Traver set up the date with the Seamen.\n\nNext week's title match is scheduled for 10:15 PM as the Axemen look to become the first back-to-back champions in CMHL history, and the Seamen aim to win the title in their debut season. Good luck to both teams in their final hurdle to win the 2026 CMHL Championship, and thank you to both the Gulls and Toonie Tuesday on another great year.`,
  },
  {
    id: 20260314,
    title: "Final Four",
    subtitle: "Seamen, Axemen, Gulls, Toonie Tuesday advance to semifinals",
    date: "March 14, 2026",
    primaryImage: "/news-images/20260314.webp",
    images: ["newsfeed/2026-playoff-bracket-sf.webp"],
    textBody: `Our semifinal field is ready to square off with a trip to the CMHL Final on the line.\n\nThree quarterfinal matchups were played at the Gale Centre last night to determine our semifinalists. In the opener, the (1) Seamen responded after an early deficit behind a Brad Pagetto hat trick, securing their spot in the next round with an 8-3 win over the (8) Bulldogs. Shortly after, the resurgent (7) Rockies gave the (2) Axemen a late scare, scoring twice with three minutes to go to make it 5-4. The Axemen would not be denied, however, adding an insurance goal and an empty-netter to punch their ticket to the semifinals. The (3) Gulls advanced following a forfeiture by the (6) Mighty Drunks, while (4) Toonie Tuesday moved on to the semis for a second straight season following a tight 5-3 win over the (5) Jagrbombs.\n\nHead of Officiating Mark Drennan returned to the ice this week, citing "Playoff bonus 💰💰💰" as his motivation. Drennan faced questions pregame in response to accusations of puck pocketing after images surfaced of league pucks being displayed on his mantle. "Got the whole set," he told reporters. Sources indicate that the removal of complimentary cafe mochas may be considered as possible discipline.\n\nLooking ahead to next week, the semifinal matchups are set with tentative game times. First, the (1) Seamen face (4) Toonie Tuesday at 8:00pm. The Seamen took the season series 2-1 over Toonie Tuesday, though the Toonies won most recently 5-3 on February 6 behind a three-point night by Will Jackman. The late slot features a rematch of the last two CMHL Finals, as the defending champion (2) Axemen face off against the (3) Gulls at 9:00pm. The Axemen won the season series 2-1, including a 9-5 victory on January 23 in which CMHL Final MVP Jacob Saddler scored three and chipped in on three more in a six-point effort in the win.\n\nBoth games promise to be competitive as the league inches closer to crowning the 2026 CMHL Champion. Good luck to the four remaining teams, and thank you to the Bulldogs, Jagrbombs, Mighty Drunks, and Rockies for a great season.`,
  },
  {
    id: 20260307,
    title: "2026 CMHL Playoff Field Set",
    subtitle: "2026 regular season comes to an end and sets up quaterfinals",
    date: "March 7, 2026",
    primaryImage: "/news-images/20260307.webp",
    images: ["newsfeed/2026-playoff-bracket-qf.webp"],
    textBody: `After last night’s final games wrapped up the regular season, the 2026 CMHL Playoffs are set to begin next Friday.\n\nThe 7pm timeslot sees the two newcomers to the league square off as the (1) Seamen battle the (8) Bulldogs. At 8pm, an Original Four clash features the defending champion (2) Axemen taking onthe recently rejuvenated (7) Rockies. Immediately after, at 9pm,the (3) Gulls begin their playoff quest to win their second title in three years as they facethe (6) Mighty Drunks. Finally, at 10pm,the (4) Toonie Tuesday meetthe (5) Jagrbombs in what should be a tightly contested matchup.\n\nWe would like to thank all ofthe players and supporters ofthe league as we enterthe final three weeks ofthe season. Good luck to all eight teams in their quest to winthe CMHL Cup.`,
  },
  {
    id: 20251010,
    title: "CMHL Returns",
    subtitle:
      "New season of CMHL arrives as the league expands to eight teams with the addition of two new teams",
    date: "October 10, 2025",
    primaryImage: "/news-images/20251010.webp",
    images: ["other/league-cup-transparent.webp"],
    textBody: `Welcome to the 2025-26 CMHL Season!\n\nThe CMHL is proud to welcome players, fans, and families to the 3rd season of the Canucks Men's Hockey League! After two thrilling years of competitive hockey, the league continues to grow, and this season promises to be the most exciting yet.\n\nLast season ended in dramatic fashion as the Axemen clinched their first-ever CMHL Cup in a nail-biting 3-2 victory over the Gulls. After falling short to the Gulls in the previous year’s final, the Axemen returned with determination to hoist the prestigious CMHL Cup.\n\nThis season, we’re thrilled to introduce two new franchises to the CMHL family. The Seamen, coming over from the CYO League in St. Catharines, bring a legacy of success and are eager to make waves in Niagara Falls. With a strong core and championship pedigree, they’re sure to be a team to watch. Also entering the league, the Bulldogs are brand-new franchise with fresh energy and ambition eager to leave their mark on the CMHL. Their arrival adds even more depth and excitement to the league.\n\nAlong with the other six returning teams, the race for the CMHL Cup is wide open. Will the Axemen defend their title? Can the Gulls reclaim their crown? Or will a new contender rise to the top?\n\nThe CMHL is excited to drop the puck on another successful season of hockey at the Gale Centre. Good luck to all teams, and we look forward to seeing you on the ice!`,
  },
  {
    id: 20250323,
    title: "Axemen Edge Gulls, Claim Title",
    date: "March 23, 2025",
    subtitle:
      "Axemen earn first franchise title as they avenge last year's title match defeat against the Gulls",
    primaryImage: "/news-images/20250323.webp",
    images: [
      "newsfeed/2025-03-23/image1.jpeg",
      "newsfeed/2025-03-23/image2.jpeg",
      "newsfeed/2025-03-23/image3.jpeg",
      "newsfeed/2025-03-23/image4.jpeg",
      "newsfeed/2025-03-23/image5.jpeg",
      "newsfeed/2025-03-23/image6.jpeg",
      "newsfeed/2025-03-23/image7.jpeg",
      "newsfeed/2025-03-23/image8.jpeg",
      "newsfeed/2025-03-23/image9.jpeg",
      "newsfeed/2025-03-23/image10.jpeg",
      "newsfeed/2025-03-23/2025-playoff-bracket-f.webp",
    ],
    textBody: `Our champion has been decided. In a game between two CMHL giants, the (3) Axemen overcame years of adversity, avenged last year’s loss, and claimed their first title by beating the (1) Gulls 3-2 on Friday night.\n\nFans who were late for the game missed an exciting start as the Gulls’ Jaret Chipman got the action started by burying the opening goal just 49 seconds into the game. The lead was short lived however as Josh Soares’ rip at 1:51 of the first quickly matched the score for the Axemen. Scoring in the first wasn’t done, however, as the Gulls answered right back at 6:35 as Chipman put away his second of the game to reclaim the Gulls’ lead. It would be the last time the Gulls ever saw the lead as just over two minutes later Matthew Thorpe responded to tie the game back up for the Axemen at 8:28.\n\nWith a 2-2 tie heading into the second, at 5:58 from just outside the blue paint, CMHL Championship Game MVP Jacob Saddler tucked away the decisive goal as the Axemen took the 3-2 lead and never looked back.\n\nA thrilling title game lived up to the billing as the encore to last year’s 5-4 overtime title match between the two clubs. Goalies Cassidy Traver (Axemen) and Kyle Underhill (Gulls) made multiple athletic, point-blank stops on both ends and gave their respective teams a chance to win the title. Ultimately, the Axemen prevailed to have their names forever etched onto the trophy as the 2024-25 CMHL Champions.\n\nWe’d like to extend all six teams, their players, coaches, and fans as well as our officiating crew and scorekeepers a thank you for a tremendous second season of the CMHL as your ongoing contributions make our league a success. We look forward to seeing you back next season as we continue to grow the CMHL. Check back in here throughout the offseason for league updates.`,
  },
  {
    id: 20250317,
    title: "Repeat or Revenge?",
    subtitle:
      "Gulls, Axemen to square off in final for second straight years after earning semifinal victories",
    date: "March 17, 2025",
    primaryImage: "/news-images/20250317.webp",
    images: [
      "newsfeed/2025-03-17/2025-playoff-bracket-f.webp",
      "newsfeed/2025-03-17/image1.jpeg",
      "newsfeed/2025-03-17/image2.jpeg",
      "newsfeed/2025-03-17/image3.jpeg",
      "newsfeed/2025-03-17/image4.jpeg",
      "newsfeed/2025-03-17/image5.jpeg",
      "newsfeed/2025-03-17/image6.jpeg",
      "newsfeed/2025-03-17/image7.jpeg",
      "newsfeed/2025-03-17/image8.jpeg",
      "newsfeed/2025-03-17/image9.jpeg",
      "newsfeed/2025-03-17/image10.jpeg",
      "newsfeed/2025-03-17/image11.jpeg",
      "newsfeed/2025-03-17/image12.jpeg",
    ],
    textBody: `The 2025 CMHL championship game is set for a rematch from 2024 after Friday night's semifinals gave us our two finalists.\n\nThe (1) Gulls advance after knocking off the (5) Jagrbombs, 5-1. A tightly contested 1-1 game into the third played to an exciting opening semifinal before four Gulls goals in 2:49 (two by John Pascente, and one each from Nick Bosco and Kyle Whalen) midway through the third gave the Gulls the decisive victory.\n\nIn the late window, two heavyweight contenders battled to determine our second finalist. With a 3-2 lead for the (3) Axemen over (2) Toonie Tuesday heading into the third, the Axemen shut the door on any Toonie Tuesday comeback with two late third period goals in 24 seconds to seal a 5-2 victory.\n\nOur championship final is now set with a (1) Gulls and (3) Axemen showdown in a rematch of last year's title game. The Axemen hope to avenge last year's heartbreaking overtime loss, while the Gulls aim to repeat as back-to-back CMHL Champions.\n\nPuck drops 9:30pm this Friday, March 21, Rink 3 at the Gale. Good luck to both teams.`,
  },
  {
    id: 20250311,
    title: "2025 CMHL Semifinals Set",
    subtitle:
      "Axemen beat Rockies, Jagrbombs triumph Mighty Drunks to advance to semifinals",
    date: "March 11, 2025",
    primaryImage: "/news-images/20250311.webp",
    images: ["newsfeed/2025-playoff-bracket-sf.webp"],
    textBody: `The 2025 CMHL semifinals are now set after last weekend's games rounded out our final four.\n\nIn the early window, the (3) Axemen advanced with a decisive 5-1 victory over the (6) Rockies. Later action saw the (5) Jagrbombs win a tightly contested quarterfinal against the (4) Mighty Drunks, 3-1.\n\nOur semifinal matchups are set for this Friday at the Gale with the (1) Gulls squaring off against (5) Jagrbombs at 9:15pm, and (2) Toonie Tuesday meeting the (3) Axemen immediately after at 10:15pm.\n\nThe winner of each matchup will advance to the second annual CMHL Final next Friday, March 21, 2025 at 9:30pm. Good luck to our semifinalists.`,
  },
  {
    id: 20250302,
    title: "2025 CMHL Playoffs Begin",
    subtitle:
      "Gulls, Toonie Tuesday earn byes as four others are set to square off in quarterfinals",
    date: "March 2, 2025",
    primaryImage: "/news-images/20250302.webp",
    images: ["newsfeed/2025-playoff-bracket-qf.webp"],
    textBody: `Thank you everyone for a great regular season! Final stats and standings for the 2024-25 CMHL regular season has been updated.\n\nCongratulations to the (1) Gulls and (2) Toonie Tuesday for receiving byes to the semifinals. Our quarterfinal matchups begin this upcoming Friday with the (3) Axemen taking on the (6) Rockies at 8:15pm, and the (4) Mighty Drunks facing off against the (5) Jagrbombs at 9:15pm.\n\nPlease note, the next round of the playoffs will be reseeded where the lowest remaining seed will play the Gulls, with the other quarterfinal winner playing Toonie Tuesday.\n\nPlayoff OT/Shootout Format:\n- 3-on-3 for 5 minutes.\n- If there is still no score after OT, shootout best-of-5 shooters.\n- No same skaters in shootout. Shootout continues if tied after 5 shooters each in a best of 1 per round.\n- No skater can be used again until team has run out of skaters and then they must start from beginning again.\n\nGood luck to everyone!`,
  },
  {
    id: 20240725,
    title: "Gulls Win Inaugural CMHL Season",
    subtitle:
      "Gulls win instant classic and claim league's first title in victory over the Axemen",
    date: "July 25, 2024",
    primaryImage: "/news-images/20240725.webp",
    images: ["newsfeed/gulls-win-2024.webp"],
    textBody: `A back and forth affair between the Gulls and Axemen played to an exciting title match. The Axemen quickly jumped out to a commanding lead before the Gulls dug deep and mounted a comeback to push the game into overtime. After successfully stealing the puck behind the net from an Axemen defender, Nick Bosco found Cesare Caldaroni who fired home the championship clinching goal. Congratulations to the Gulls on winning the inaugural league title!\n\nThank you to all players for making our first year a success and we look forward to next season.\n\nCheck back in the near future for details.`,
  },
  {
    id: 20231003,
    title: "Welcome to the CMHL",
    subtitle:
      "New league founded in Niagara Falls, Ontario set to debut in October 2023",
    date: "October 3, 2023",
    primaryImage: "/news-images/20231003.webp",
    images: ["logos/logo-transparent-black.webp"],
    textBody: `Welcome to the official website of the Canucks Men's Hockey League (CMHL) based out of the Gale Centre Arena in Niagara Falls, Ontario. We are excited to drop the puck on our inaugural season with our first four teams - Axemen, Gulls, Rockies, and Whiskey Dekes. \n\nAll players are expected to register, know their team's schedule, and familiarize themselves with league rules and information. \n\nInterested in registering a team for next season? Please reach out to us at cmhlniagara@gmail.com`,
  },
];
